pom.xml
URL have been changed quite a long time ago, and started to fail badly recently. Time to fix those.
Ping @rtyler
=> [INFRA-588] maven.j.o => repo.j.o

pom.xml
It is required for [JENKINS-37565](https://issues.jenkins-ci.org/browse/JENKINS-37565)
I have not touched the default version just in case other components still need Java 6.
@reviewbybees @jenkinsci/code-reviewers
=> [JENKINS-37565] Allow specifying custom java.level

pom.xml
The most of the configurations come from Plugin POM. In longer term we need to merge two POMs somehow (e.g. make this POM a parent for Plugin POM), but now I just moved the common Enforcer and Animal Sniffer checks
Downstream PRs: 
* https://github.com/jenkinsci/maven-interceptors/pull/12
* https://github.com/jenkinsci/remoting/pull/188
* https://github.com/jenkinsci/jenkins/pull/2985
@reviewbybees esp. @jglick since it enforces upper bounds in Jenkins core && may collide with https://github.com/jenkinsci/jenkins/pull/2956
=> Update Maven Enforcer, add Animal Sniffer and Test annotations

pom.xml
Filed downstream https://github.com/jenkinsci/jenkins/pull/2998 to verify this change does not break something.
```
$ mvn versions:display-plugin-updates
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Jenkins 1.39-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- versions-maven-plugin:1.3.1:display-plugin-updates (default-cli) @ jenkins ---
[INFO] artifact com.cloudbees:maven-license-plugin: checking for updates from cloudbees-internal
[INFO] artifact org.apache.maven.plugins:maven-assembly-plugin: checking for updates from cloudbees-internal
[INFO] artifact org.apache.maven.plugins:maven-changelog-plugin: checking for updates from …
```
=> [JENKINS-46603] Upgrade plugins (esp. for JDK9 compat)

pom.xml
The version was just released with a few fixes, including two from @jglick and @Vlatombe which improves corruption detection and hints about the problematic files. So we should propagate that usage.
https://github.com/mojohaus/extra-enforcer-rules/milestone/5?closed=1
@reviewbybees
=> Bump to extra-enforcer-rules 1.0-beta-7

pom.xml
I am tired of setting up FindBugs for every core component/plugin separately, so I would like to generalize it in the parent POM.
The current implementation is taken from the https://github.com/jenkinsci/plugin-pom with some extra patches for the core support.
=> Run FindBugs by default in components

incrementals.md, pom.xml
[JENKINS-50692](https://issues.jenkins-ci.org/browse/JENKINS-50692)
Analogous to https://github.com/jenkinsci/plugin-pom/pull/100.
=> [JEP-305] Incrementals profiles

pom.xml
Trying to fix the problem that necessitated an emergency workaround in https://github.com/jenkinsci/jenkins/pull/3441.
=> [JENKINS-51247] Always use source:jar-no-fork, not source:jar

pom.xml
See comment in [MNG-6405](https://issues.apache.org/jira/browse/MNG-6405). Cleans up from #25 if we assume people are using the latest Maven release with https://github.com/apache/maven/pull/168. Not proposing immediate merge since I am not sure when CI systems will be updated, and currently we are not properly containerizing our builds.
=> [JENKINS-51247] Superpom as of MNG-5940 in Maven 3.5.4 obsoletes the need for a MNG-6405 workaround

pom.xml
I suspect #27 does not work as is:
mvn incrementals:reincrementalify
does not work without this patch. You have to specify
mvn io.jenkins.tools.incrementals:incrementals-maven-plugin:reincrementalify
`plugin-pom` already had this configuration block at top level so that
mvn incrementals:incrementalify
would work OOTB on a new plugin. That is less of a concern for this POM, which is expected to be used for Incrementals only in a handful of cases, but also potentially applicable.
=> Move incrementals-maven-plugin configuration out of a profile, so the default plugin prefix is available

pom.xml
There are lost of updates to pick actually, I just try to limit testing scope for now.
* Maven Compiler: support of multi-release JARs
* Animal Sniffer: Support of Java 10+ formats and multi-release JARs
* Javadoc Plugin: Better support of Java 9+ constructs + stability fixes
@jenkinsci/sig-platform
=> Update Maven plugins to versions with Java 9+ compatibility fixes.

pom.xml
cc @jenkinsci/java11-support 
Full diff of the updated dependency: https://github.com/mojohaus/extra-enforcer-rules/compare/extra-enforcer-rules-1.0-beta-7...extra-enforcer-rules-1.1
=> Update to extra-enforcer-rules with JDK 11 support

pom.xml
Analogue of https://github.com/jenkinsci/plugin-pom/pull/196.
Was unable to verify that this allows the `jdk11` profile to be deleted from `jenkinsci/jenkins/pom.xml`, since I could not compile Jenkins core at all under Java 11 (error in `CrontabParser`). I did at least confirm that it causes `-source 8` to appear in `core/target/apidocs/options` as expected when using `-Ddebug`.
=> Set source level for maven-javadoc-plugin

pom.xml
Modeled after jenkinsci/plugin-pom#128. I tested the result against Jenkins core, Remoting, and the Swarm client. In each case, I was able to switch over to SpotBugs smoothly, and I even found a few new warnings in each upstream project after I had switched.
=> Switch to SpotBugs

.dependabot/config.yml
Inspired by [#44 (comment)](https://github.com/jenkinsci/pom/pull/44#pullrequestreview-300811649). I'm not the maintainer of this repository, so I don't think it's proper for me to file the Jira ticket to enable Dependabot. But I can at least assist in supplying a Dependabot configuration file.
CC: @jenkinsci/hacktoberfest
=> Add Dependabot configuration file

pom.xml
Bumps `test-annotations` from 1.2 to 1.3.
CC: @jenkinsci/hacktoberfest
=> Update test-annotations from 1.2 to 1.3

pom.xml
The mailing list was removed a while ago, but the naming was obsolete here and in Jenkins metadata.
P.S: Yes, just another kinda useful pull request for release drafter
=> Modify the Jenkins Japanese user discussion links

pom.xml
I added [find-sec-bugs ](https://github.com/find-sec-bugs/find-sec-bugs) plugin to spotbugs. I don't think that it should be merged right away, because there are a lot of findigs in Jenkins. This is here for discussion, if this is useful at all.
But I found for example:
https://github.com/jenkinsci/jenkins/pull/4363
=> Add findsecbugs plugin to spotbugs

pom.xml
Introduce version for spotbugs annotations for re-use in jenkins bom.
Follow-Up of: https://github.com/jenkinsci/jenkins/pull/4689
=> Introduce version for spotbugs annotations for re-use in jenkins bom

pom.xml
Follow-up toy the suggestion from @timja in #49 . Maven Idea plugin is no longer needed, because IDEA can import Maven projects on its own. Since the plugin is retired, let's remove it.
https://maven.apache.org/plugins/maven-idea-plugin/
=> Remove maven-idea-plugin from the Parent POM

pom.xml
I am working on adding code coverage reporting to https://github.com/jenkinsci/jenkinsfile-runner/ . Unfortunately JaCoCo profile cannot run with the default configuration of the Maven Sure Fire plugin. JaCoCo plugin installs the Java agent and passes configuration through `argLine`. This argline gets suppressed by the historical SUREFIRE-1588 patch.
This patch fixes the behavior
=> Pass `argLine` to Maven Surefire Plugin so that agents can be connected to the tests run

pom.xml
This avoids problems if the argLine doesn't end up getting defined by something else.
This is a follow-on to #138
Without defining the argLine the previous change may break some projects that use this parent. For one example see jenkinsci/remoting#407. Once this is merged in, Remoting can update to the latest parent without needing to define argLine itself.
=> Define an empty argline property.

pom.xml
Porting https://github.com/jenkinsci/plugin-pom/blob/105ec85c7cb014d83f30622aeda6ae8a7e0a86d6/pom.xml#L1434-L1446 as it is used by https://github.com/jglick/jenkins-maven-cd-action/blob/8d95c384dedf1e459b8fe30fb789eb6a5bcf2fd1/run.sh#L4 and so we would need this to be present if we were using JEP-229 on non-plugin repositories.
=> Copy -Pquick-build from plugin-pom 4.x

pom.xml
A port of jenkinsci/plugin-pom#415 for the parent POM for Jenkins core and libraries. See stapler/stapler#226 and [the Maven documentation](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#parameters). Once widely adopted, this would allow us to use reflection rather than ASM in Stapler for discovering method parameters.
=> Generate metadata for reflection on method parameters

.github/workflows/changelog.yaml
I released https://github.com/jenkinsci/pom/releases/tag/jenkins-1.66 and the release notes weren't there straight after, this should be quicker and more reliable
=> Add release drafter as GitHub action

pom.xml
Remove deprecated findbugs properties, directly use spotbugs properties.
Jenkins uses the spotbugs properties after https://github.com/jenkinsci/jenkins/pull/5746
=> Remove deprecated findbugs properties, directly use spotbugs properties

pom.xml
Amends #196. Complements jenkinsci/plugin-pom#456, specifically
https://github.com/jenkinsci/plugin-pom/blob/843c0894e7b8eae9451b6adfe0ac2895d470f512/pom.xml#L540-L541
Without this PR, core cannot be upgraded to the latest snapshot parent POM because of `requireUpperBoundDeps` errors in `servlet-api`.
Tested by building core with the parent POM from this PR.
=> Exclude `servlet-api` from `requireUpperBoundDeps`

pom.xml
`plugin-pom` already has this exclusion, and without this I get annoying errors in some cases like
```
Require upper bound dependencies error for com.google.code.findbugs:jsr305:3.0.1 [provided] paths to dependency are:
+-org.jenkins-ci.main:cli:2.324-SNAPSHOT
+-com.github.spotbugs:spotbugs-annotations:4.5.0 [provided]
+-com.google.code.findbugs:jsr305:3.0.1 [provided] (managed) <-- com.google.code.findbugs:jsr305:3.0.2 [provided]
```
CC @jglick
=> Ignore `jsr305` warnings

pom.xml
`javax.servlet:servlet-api` is a banned dependency, so let's enforce that core and core components don't use it. The only exception to this rule is version 0, which is a custom version that we have deployed to `repo.jenkins-ci.org` which has an empty JAR.
=> Ban `javax.servlet:servlet-api`

pom.xml
Ban Apache Log4j 2.15.0-rc1 and earlier via Maven Enforcer.
=> Ban vulnerable versions of Apache Log4j 2

pom.xml
Like jenkinsci/plugin-pom#449 and jenkinsci/plugin-pom#502, but for `jenkinsci/pom`.
=> Set `-release` flag to `java.level` when running on JDK9+ & EOL `java.level.test`

pom.xml
See [JENKINS-67960](https://issues.jenkins.io/browse/JENKINS-67960) and [MCOMPILER-346](https://issues.apache.org/jira/browse/MCOMPILER-346). I have run into this bug repeatedly while working on Jenkins, most recently in jenkinsci/acceptance-test-harness#733.
When compiling Jenkins code with compilation errors with Java 11, [MCOMPILER-346](https://issues.apache.org/jira/browse/MCOMPILER-346) is frequently encountered. If you encounter it with `-source 8`, you get a `NullPointerException`. If you encounter it with `-source 11`, you get an `AssertionError`. Either way, you do not get a readable message with the compilation error. Therefore, you have no idea what you need to fix in order to get the code to compile.
TBD. MCOMPILER-346 has remained open since June 28, 2018. I submitted a …
=> [JENKINS-67960] Work around MCOMPILER-346

pom.xml
[SUREFIRE-1588](https://issues.apache.org/jira/browse/SUREFIRE-1588) has not seen any activity since 2018, so I think this workaround is no longer necessary. I tested this locally with Java 8 and Java 11 on core and `jenkins-test-harness` and had no issues.
=> Remove obsolete workaround for SUREFIRE-1588

pom.xml
Like https://github.com/jenkinsci/plugin-pom/pull/522 but for `pom` rather than `plugin-pom`.
Deployment plan: There are only a dozen or so core components, so I plan on just making a pass through them as I upgrade to this release of `pom` and deleting `java.level` manually.
=> Deprecate `java.level`

pom.xml
Straightforward sideport of https://github.com/jenkinsci/plugin-pom/pull/523 from `plugin-pom` to `pom`. The main change of substance here is that we are now skipping Animal Sniffer when `release` is set (i.e., when building with a Java 9 or later compiler, even when we build Java 8 bytecode). The switch from XML configuration to properties is not necessary in this repository as it was in https://github.com/jenkinsci/plugin-pom/pull/523 (there is no `Initializer` mojo manipulating these values for core or core components), but I think there is value in keeping these two repositories (which are largely copypasta of each other) as similar as possible in order to make it easier to sideport other changes in the future without merge conflicts.
=> Sideport of JENKINS-54842 to `pom`

pom.xml
SIdeport of https://github.com/jenkinsci/plugin-pom/pull/530 from `pom` to `plugin-pom`.
=> Setting `source` and `target` are unnecessary when setting `release`

pom.xml
Fixup to https://github.com/jenkinsci/pom/pull/248: if we avoid defining the properties for Java 9+, we don't have to clear them.
=> Avoid unnecessary defining and clearing of properties

pom.xml
Consistent with https://github.com/jenkinsci/plugin-pom/blob/c772be96e570f721b39f200de46795914884104e/pom.xml#L75=.
Why not resolve the inconsistency in the other direction? Because
```
Artifact Ids of the format maven-___-plugin are reserved for
plugins in the Group Id org.apache.maven.plugins
[…]
In the future this error will break the build.
```
=> Rename `maven-hpi-plugin.version` to `hpi-plugin.version`

pom.xml
Fix an error introduced in #259: I renamed the property in one place but not the other.
=> Fix Maven HPI plugin version

pom.xml
Amends #209. Setting `source=8` is wrong now that we are requiring Java 11. Furthermore, based on my reading of `AbstractJavadocMojo` it is dead code: whenever `release` is set, it is always used in place of `source` in that class. And we are (implicitly) setting `release` (to the correct value of 11, no less!) because `release` defaults to the value of the `maven.compiler.release` property, which we are setting to 11. So we are implicitly setting `release`, which means `source` is unused, which means it is dead code, which means it should be deleted.
=> Remove `source=8` from Javadoc configuration

pom.xml
Matching https://github.com/jenkinsci/plugin-pom/pull/356 since I noticed in https://github.com/jenkinsci/stapler/pull/370 that it is hard to see the actual diff for all the silly Javadoc warnings.
=> `-Xdoclint:all,-missing`

pom.xml
Consistent with https://github.com/jenkinsci/plugin-pom/blob/ac96d2394082c1ea3808ad59e789712162a922f9/pom.xml#L1160-L1170=
Tested in core (verified that `executable.MainTest` stopped spamming logs except when running with `-Dtest=executable.MainTest`):
```
diff --git a/core/pom.xml b/core/pom.xml
index 569d56a603..49f0d46bec 100644
--- a/core/pom.xml
+++ b/core/pom.xml
@@ -798,17 +798,6 @@ THE SOFTWARE.
<spotbugs.failOnError>true</spotbugs.failOnError>
</properties>
</profile>
-    <profile>
-      <id>all-tests</id>
-      <activation>
-        <property>
-          <name>!test</name>
-        </property>
-      </activation>
-      <properties>
-        <maven.test.redirectTestOutputToFile>true</maven.test.redirectTestOutputToFile>
-      </properties>
-    </profile>
<profile> …
```
=> [JENKINS-68919] Redirect test output to file when running all tests

pom.xml
=> upgrade maven-release-plugin to 3.0.0-M6

pom.xml
Whatever `maven-antrun-extended-plugin` is, it hasn't been updated in a decade. Better to remove it and for any consumers that still need it to remove their dependency or carry it themselves independently of the parent POM. In addition, we upgrade `maven-antrun-plugin` to the latest version, which is also consistent with the plugin POM. To test this I verified that core could be built with these changes and confirmed `maven-antrun-plugin` 3.1.0 could run the core build.
=> Upgrade Maven AntRun plugin

pom.xml
We import this in the plugin POM, so might as well import it here for consistency. It includes both JUnit 4 and JUnit 5. Once adopted by downstream consumers, they can stop pulling in the JUnit BOM themselves which should result in some code deduplication.
=> Use JUnit BOM

pom.xml
Noticed a few dead links while browsing the pom, additionally we're now using HTTPS over HTTP by now..
=> chore: Remove dead links

pom.xml
https://github.com/jenkinsci/pom/pull/302 removed the archive URLs. This adds the currently working archive URLs back.
It's unclear to me what the purpose of having this in the pom is (other than site builds) but since the entries still exist, they should be complete.
There's more wrong here, e.g. the differences between the pom and https://www.jenkins.io/mailing-lists/ are staggering, but one step at a time.
=> Add correct archive URLs

.github/dependabot.yml
@oleg-nenashev is no longer active in this repository.
=> Remove `oleg-nenashev` from `dependabot.yml`

pom.xml
Alternative to #297. This matches the Maven Javadoc plugin, which [uses the values of the `maven.compiler.source` and `maven.compiler.release` properties if defined](https://github.com/apache/maven-javadoc-plugin/blob/5b61ee915298b51a273bd88612fb346ac639d9e0/src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java#L817-L831). This alternative eliminates my two main objections to #297:
- It only works for Java 9+, thus eliminating the negative incentive to stay on Java 8
- It does not define a new API for consumers, thus not implicitly committing us to supporting arbitrary future Java versions via this mechanism. Rather this PR just makes it less likely that people who are using the existing Maven API will have  trouble with Enforcer.
I tested this by compiling Jenkins core …
=> Define Enforcer Java version in terms of `maven.compiler.release`

pom.xml
The version of the SpotBugs Maven Plugin that we are using already defines the `failOnError`, `effort`, `threshold`, and `excludeFilterFile` mojo parameters to the values of the `spotbugs.failOnError`, `spotbugs.threshold`, `spotbugs.effort`, or `spotbugs.excludeFilterFile` properties if set, with the same defaults as ours if these properties are not set (see https://github.com/spotbugs/spotbugs-maven-plugin/blob/f01a7f6b99da3d2e6dcdbddd20f0b4e4dfac73fa/src/main/groovy/org/codehaus/mojo/spotbugs/BaseViolationCheckMojo.groovy). As such it is completely redundant to declare these defaults ourselves and configure the mojo with them. To test this, I compiled the Swarm client  with these changes and observed that the `spotbugs.excludeFilterFile` and `spotbugs.threshold` settings still took …
=> Remove duplicate SpotBugs defaults

pom.xml
Picking up https://github.com/jenkinsci/plugin-pom/blob/efa3afff274c907f0404cda9bdf91195ba63cd6c/pom.xml#L1138-L1161 from the plugin POM. To test this I removed `<spotbugs.excludeFilterFile>` from Jenkins core, observed SpotBugs errors as expected, then observed that the errors went away after I renamed `src/spotbugs/spotbugs-excludes.xml` to `src/spotbugs/excludesFilter.xml`.
=> Define a standard SpotBugs exclude filter file

pom.xml
`org.mortbay.jetty:maven-jetty-plugin` has not been released since 2008 and was removed in `plugin-pom` in jenkinsci/plugin-pom@24b09578ef07f5b759283d6778f80e479826c6a7. I am not aware of any usages in Jenkins core components.
=> Remove `org.mortbay.jetty:maven-jetty-plugin`

pom.xml
Consistent with https://github.com/jenkinsci/plugin-pom/blob/7a900a501a29781b2c3b2b2a1b9fbcc6aecb5862/pom.xml#L684-L705. To test this change I ran a core build with `mvn clean verify -DskipTests` and verified that the SpotBugs XML files were generated as before.
=> Make SpotBugs configuration consistent with `plugin-pom`

pom.xml
I find it easier to compare this `pom.xml` with that of `plugin-pom` when the entries are sorted. To test this I compiled Jenkins core successfully with these changes.
=> Sort `<pluginManagement>` entries by group ID and artifact ID

pom.xml
Sorcerer does not work with Java 11 and we ripped it out of Jenkins core in jenkinsci/jenkins#5960.
=> Remove `maven-sorcerer-plugin`

pom.xml
Amending #340 to sort first by scope, then group ID and artifact ID.
=> Sort `<dependencyManagement>` section by scope, group ID, and artifact ID

pom.xml
See #42. A GItHub code search for `user:jenkinsci path:pom.xml "gmaven-plugin"` only yielded results in plugins (not affected by changes to this POM) and https://github.com/jenkinsci/lib-groovy-guice-binder/blob/ed3447b4ed59aa487cda6690072211c1678de3c6/pom.xml#L16-L30 (which declares an explicit version, so it is also not affected by changes to this POM), so this plugin is safe to remove. To test this change I successfully built Jenkins core with the changes from this PR (modulo having to fix a SpotBugs warning from an unrelated PR).
=> Remove `gmaven-plugin`

pom.xml
This workaround was needed prior to the release of OpenJDK 11.0.16. We're now running 11.0.17 on Jenkins project infrastructure, so this workaround is no longer necessary.
=> Remove `forceJavacCompilerUse` workaround

pom.xml
These two Maven plugins live in the same Git repository and are released in lockstep, so it does not make sense to use a different property for each one. This PR simplifies the version management by using a single property for both.
=> Consolidate `maven-surefire-plugin.version` and `maven-surefire-report-plugin.version`

pom.xml
`plugin-pom` uses the property name `stapler-plugin.version` for the version of the Stapler plugin. This PR makes `jenkinsci/pom` consistent by using the same name here as well.
=> Use a name for the Stapler plugin property that is consistent with `plugin-pom`

pom.xml
This POM includes a number of Maven plugins that are not present in the plugin POM, are not consumed by Jenkins core or any Jenkins core components, and which are obsolete and have not been released in years. This is a maintenance burden, so this PR removes them. In the unlikely case that any consumers still needs one of these Maven plugins, they can declare its version themselves rather than getting it from the parent POM. To test this PR I successfully compiled Jenkins core with these changes.
=> Remove obsolete Maven plugins

pom.xml
Side-port of https://github.com/jenkinsci/plugin-pom/pull/666 to the POM for core and core components.
=> Inline Maven property `incrementals.url` for Maven 4 support

pom.xml
The list of version properties is easier to read and edit when it is kept in sorted order, like that in `plugin-pom`. Having it in sorted order also makes it easier to check how many tiny differences remain between these two POMs.
=> Sort version properties

pom.xml
Elsewhere in this POM (and in the logic for this profile in the plugin parent POM), the default `groupId` of `org.apache.maven.plugins` is omitted, so omit it here as well for both internal consistency and consistency with the logic for this profile in the plugin parent POM.
=> Remove unnecessary default group ID

pom.xml
The Maven default is once per day and the plugin parent POM does not customize this. This parent POM customizes it to once a week. I see no need for this customization. Removing it brings us closer to both the Maven defaults and the plugin parent POM.
=> Remove unnecessary customization of remote repository update frequency

pom.xml
This isn't in the plugin POM and I see no reason why anyone should ever be running Maven without specifying a goal. Seems simpler to remove this bizarre customization and stick with the Maven default (and Jenkins plugin default) of forcing consumers to specify a goal.
=> Remove `defaultGoal`

pom.xml
Eliminate some pointless inconsistency between this POM and the plugin POM by syncing some comments and moving some configuration from one block to another. It doesn't matter which block the configuration is in, as only one goal was being executed. This was effectively a mistake made when the change was first side-ported.
=> Eliminate some pointless inconsistency

pom.xml
Almost all actual plugin configuration in this POM happens in the `<plugins>` section rather than the `<pluginManagement>` section, which is mostly used to just define versions. This PR makes `maven-release-plugin` internally consistent within this repository. As a bonus it matches the way it is done in the plugin POM as well. We also swapped the order of the two elements in the list to match the order in `plugin-pom`.
=> Define `releaseProfiles` in `<plugins>` section rather than `<pluginManagement>` section

pom.xml
The use of a comma followed by a square bracket is consistent with neither [the version range specification](https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html) nor https://github.com/jenkinsci/plugin-pom/pull/89. This PR makes it consistent with both.
=> Fix `requireJavaVersion` range

pom.xml
As of jenkinsci/jenkins#7478 we no longer have `javax.servlet:servlet-api` version 0 in our dependency tree, so we can now clean up this logic and ban all versions of it rather than banning all versions except version 0. To test this I compiled Jenkins core with these changes.
=> Ban `javax.servlet:servlet-api` version 0

pom.xml
I can't see a reason for these excludes, since our bytecode version is Java 11 and these libraries are for older Java versions. To test this I successfully compiled Jenkins core with these changes.
=> Remove unnecessary `enforceBytecodeVersion` excludes

pom.xml
https://spotbugs.github.io/spotbugs-maven-plugin/spotbugs-mojo.html says that it is deprecated and gives no reason for the deprecation.  Since the value was false, it seems safe to remove the setting.
Fixes #400
https://github.com/jenkinsci/plugin-pom/pull/722 is the matching pull request in the plugin pom.
=> Remove deprecated spotbugsXmlOutput setting

pom.xml
For the Launchable work, we need a way to get the commit hash from a given artifact in order to define a Launchable build. While this can be derived at runtime by dereferencing the tag back to a commit using the GitHub API, it is simpler to bake this information into the relevant artifact in the first place. This PR adds the following to `MANIFEST.MF` for all core component `.jar` files (including shaded JARs) and `.war` files:
- `Specification-Title`: `${project.name}`
- `Specification-Version`: ${MAJOR.MINOR}`
- `Implementation-Title`: `${project.description}`
- `Implementation-Version`: `${project.version}`
- `Implementation-Build`: Git hash
The last of these is not part of the default implementation entries but is provided by [Build Number Maven …
=> Add default specification entries, default implementation entries, and Git hash to `MANIFEST.MF`

pom.xml
I see no straightforward way to fix #425, so this PR simply redefines the expected behavior to be the new behavior rather than the old behavior by removing `spotless.check.skip` from any Maven profiles where it is defined, thus shifting the burden on the consumer to pass in `-Dspotless.check.skip` anywhere they were previously passing in `-Pquick-build`. While a minor burden, this seems good enough especially given the lack of any obvious alternatives.
Fixes #425.
=> Remove `spotless.check.skip` from `quick-build profile`

pom.xml
`hamcrest-core` is deprecated since 2019, in favor of `hamcrest` where the logic lives on since then.
Consumers are advised to replace hamcrest-core with hamcrest in their pom, if not already done.
=> Replace `hamcrest-core` with `hamcrest`

.github/workflows/changelog.yaml
Release drafter does no longer rely on additional tag specifications.
=> Simplify release-drafter workflow

pom.xml
Sideport of https://github.com/jenkinsci/plugin-pom/pull/847 to `jenkinsci/pom`.
See https://github.com/jenkinsci/plugin-pom/pull/847.
=> Add PowerMock to banned dependencies

pom.xml
Reverts jenkinsci/pom#498 because this new version results in dozens of noisy SpotBugs violations of questionable value.
=> Revert "Bump com.github.spotbugs:spotbugs-maven-plugin from 4.7.3.6 to 4.8.1.0"

pom.xml
Like https://github.com/jenkinsci/plugin-pom/pull/864, but for `jenkinsci/pom`.
See https://github.com/jenkinsci/plugin-pom/pull/864.
=> Ban Jenkins test harness in compile scope

pom.xml
This sets `spotless.skip`, a [fairly recent](https://github.com/diffplug/spotless/blob/1ad019da39f8994d5b7ccd86a536678cb38fbdea/plugin-maven/CHANGES.md?plain=1#L101-L103) property that [takes precedence](https://github.com/diffplug/spotless/blob/1ad019da39f8994d5b7ccd86a536678cb38fbdea/plugin-maven/src/main/java/com/diffplug/spotless/maven/AbstractSpotlessMojo.java#L244-L259) over `spotless.check.skip`.
See [JENKINS-72956](https://issues.jenkins.io/browse/JENKINS-72956), and https://github.com/jenkinsci/jenkins/pull/9124 for recent backstory. Amends #427, addresses #425 as originally requested.
Just a quick local snapshot install, used in the core build with `-Pquick-build`.
```[tasklist]
```
=> [JENKINS-72956] Skip Spotless in quick-build profile

pom.xml
Consumers of this POM don't use `maven-pmd-plugin` anymore.
`rg maven-pmd-plugin` showed no consumers of this repository.
=> Remove `maven-pmd-plugin`

pom.xml
Reverts jenkinsci/pom#590
After deploying this today, I started getting these errors from Jenkins Maven plugins:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.20.0:site (default-site) on project jellydoc-maven-plugin: Failed to create context for skin: Cannot use skin: has [1.11.1,2.0.0-M1) Doxia Sitetools prerequisite, but current is 2.0.0-M19 -> [Help 1]
```
=> Revert "Bump org.apache.maven.plugins:maven-site-plugin from 3.12.1 to 3.20.0"

pom.xml
With the newer version, I get the following error in core taglib generation:
```
[WARNING] An issue has occurred with maven-project-info-reports-plugin:3.7.0:ci-management report, skipping LinkageError 'void org.apache.maven.doxia.sink.Sink.verbatim()', please report an issue to Maven dev team.
java.lang.NoSuchMethodError: 'void org.apache.maven.doxia.sink.Sink.verbatim()'
at org.apache.maven.reporting.AbstractMavenReportRenderer.verbatimLink (AbstractMavenReportRenderer.java:384)
at org.apache.maven.report.projectinfo.CiManagementReport$CiManagementRenderer.renderBody (CiManagementReport.java:143)
at org.apache.maven.reporting.AbstractMavenReportRenderer.render (AbstractMavenReportRenderer.java:93)
at org.apache.maven.report.projectinfo.CiManagementReport.executeReport …
```
=> Downgrade `maven-project-info-reports-plugin` to last working version

pom.xml
I often find myself forgetting to apply spotless before committing.
On some repositories, I have set up a pre-commit git hook running `mvn spotless:check`. However, this has to be set up on each repository that has spotless check enabled, and disabled on those which don't.
I think this goes one step further, by defining a conventional maven profile `may-spotless-apply` that will run `spotless:apply` *only* if spotless is enabled for the given repository.
This allows any user to incorporate `-Pmay-spotless-apply` as part of their usual build command (or defined in their maven settings active profiles section), and have `spotless:apply` automatically called if the project has it enabled.
See also https://github.com/jenkinsci/plugin-pom/pull/1017
=> Add 'may-spotless-apply' profile

pom.xml
[Palantir Java Format 2.73.0](https://github.com/palantir/palantir-java-format/releases/tag/2.73.0) was released last week.
The git client plugin use of `spotless` needs the Palantir Java Format upgrade to 2.73.0 in order to run `spotless` with Java 25.
The Palantir Java Format upgrade does not seem to be required for Jenkins core to run `spotless` with Java 25.  This will keep the core pom version of Palantir Java Format consistent with the version needed in the plugin pom.
Matching pull request submitted to plugin pom:
* https://github.com/jenkinsci/plugin-pom/pull/1176
Confirmed that `mvn spotless:apply` succeeds with Java 25 EA build 28 on Jenkins core with or without this change.
Confirmed that `mvn spotless:apply` makes no formatting changes in Jenkins core with this change.
=> Use Palantir Java Format 2.73.0
