jenkinsci/pom

pom.xml

Let's upgrade to last release. No specific reason/issue for this, just trying to keep things up-to-date.
I also centralized the tool version. Not sure the fact we were using different versions was on purpose (we actually [override it in Jenkins core](https://github.com/jenkinsci/jenkins/blob/8189c2cd9a2cb0a4e6d2dcf341fb818dbd9165ba/pom.xml#L606)).
See the announcement: https://groups.google.com/forum/#!msg/mojohaus-dev/1X3FFgNYB98/NWwm56D9AAAJ
I had [tested it when staged, no issue found](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mojohaus-dev/U54UXKYt8p8/7ItZA1wRCAAJ).
* Update to [animal-sniffer 1.16 release](https://groups.google.com/forum/#!msg/mojohaus-dev/1X3FFgNYB98/NWwm56D9AAAJ)
- ~~[ ] JIRA issue is well described~~
* Use the `Internal: ` prefix if …

Update to animal-sniffer 1.16

---

pom.xml

Subj. Since we add Test Annotations & Co, it makes sense to add it as well
@jenkinsci/code-reviewers

Add JUnit to Dependency Management

---

pom.xml

Apply a more global bump like in https://github.com/jenkinsci/jenkins/pull/3408
@reviewbybees esp. @daniel-beck 
See [JENKINS-50969](https://issues.jenkins-ci.org/browse/JENKINS-50969).

[JENKINS-50969] Bump to latest maven-site-plugin

---

pom.xml

See usage from `incrementals.md`.

Update versions-maven-plugin.version=2.5 so versions:set-property is available

---

pom.xml

Analogous to https://github.com/jenkinsci/plugin-pom/pull/105.

[JENKINS-51247] Simplified usage of flatten-maven-plugin

---

pom.xml

Analogue of https://github.com/jenkinsci/plugin-pom/pull/104 for other components.

Preconfigure incrementals-maven-plugin

---

pom.xml

same as https://github.com/jenkinsci/plugin-pom/pull/117 you should remove your reincrementalify done in the release scripts
Here we can see the completionGoals in use: https://github.com/jenkinsci/kotlin-v1-stdlib-jdk8-plugin/commit/afc674665f767aeec664536c8b6fb64961fda48f

[JENKINS-51658] add reincrementalify to completionGoals in might-produce-incrementals

---

pom.xml

Analogue of https://github.com/jenkinsci/plugin-pom/pull/119.

[JENKINS-51869] Require git-changelist-maven-extension to be 1.0-beta-4 or newer

---

pom.xml

https://issues.apache.org/jira/browse/MJAR-241
Same as https://github.com/jenkinsci/plugin-pom/pull/140

[JENKINS-55162] - Update to Maven JAR Plugin 3.1.1 to pick up the fix of MJAR-241

---

.github/release-drafter.yml

Same as in Plugin POM: https://github.com/jenkinsci/plugin-pom

Enable release Drafter for the repository

---

pom.xml

Update component name and description in the pom.xml to clarify the components purpose

---

README.md

This is somewhat useful pull request which should retrigger Release Drafter

Update the title in README to be more explicit about the repo's purpose

---

pom.xml

I'm not sure why the default is still set to **java 6**, so I updated the default to 8 and also updated the comment accordingly.

Update default java version to 8

---

pom.xml

same as https://github.com/jenkinsci/plugin-pom/pull/359

Enforce English Locale for JavaDoc Generation

---

pom.xml

Matches https://github.com/jenkinsci/plugin-pom/pull/375.

[JEP-229] Created a block-MRP profile

---

pom.xml

updates the localizer plugin to 1.28 (adds threadsagety support for parallel builds, and messages from XML)
https://github.com/kohsuke/localizer/compare/localizer-parent-1.26...localizer-parent-1.28

Update localizer plugin

---

pom.xml

Analogue of https://github.com/jenkinsci/plugin-pom/pull/416. Again not sure how to test this realistically.

[JENKINS-50804] Pass `-P!consume-incrementals` during `release:perform`

---

pom.xml

Combines two dependabot pull requests that need each other.  Octopus merged.
* #177 
* #187

Use enforcer 3.0.0 and matching extra enforcer rules

---

pom.xml

Consistently use two spaces for indentation.

Consistent indentation

---

pom.xml

Like jenkinsci/plugin-pom#419, but for `jenkinsci/pom`.

Require Maven 3.8.1

---

pom.xml

Consistent with https://github.com/jenkinsci/plugin-pom/blob/1910fb3f600c6d47d74fdf9ee675d2501981a26a/pom.xml#L321=.

Align Surefire version with `plugin-pom`

---

pom.xml

Port of https://github.com/jenkinsci/plugin-pom/blob/fe006ce973196bd311aa53dcdaee9fccc26e221b/pom.xml#L57-L59=
ref https://github.com/jenkinsci/stapler/pull/357#discussion_r867270322

Use UTF-8 build encoding

---

pom.xml

https://github.com/jenkinsci/jenkins/pull/6863#discussion_r923364143

Skip yarn lint in `-P quick-build`

---

pom.xml

Addresses https://github.com/mojohaus/extra-enforcer-rules/issues/225 on our end.

build: Update extra-enforcer-rules to 1.6.1

---

pom.xml

Signed-off-by: Olivier Lamy <olamy@apache.org>

[JENKINS-69198] add jenkins-release profile to attach javadoc and sources jars

---

pom.xml

https://github.com/jenkinsci/plugin-pom/pull/596

add junit 4.x to dependency management

---

pom.xml

Like https://github.com/jenkinsci/plugin-pom/pull/610 but for `jenkinsci/pom`.

Use `mockito-bom`

---

pom.xml

As of https://github.com/jenkinsci/jenkins/pull/7293 the group ID, artifact ID, version, and goal have changed.

Adapt to https://github.com/jenkinsci/jenkins/pull/7293

---

pom.xml

Like https://github.com/jenkinsci/plugin-pom/pull/629 but for `jenkinsci/pom`. To test this I verified that `mvn clean verify -DskipTests` passed on core with
```
diff --git a/pom.xml b/pom.xml
index 4595a42314..3db08a51ee 100644
--- a/pom.xml
+++ b/pom.xml
@@ -28,7 +28,7 @@ THE SOFTWARE.
<parent>
<groupId>org.jenkins-ci</groupId>
<artifactId>jenkins</artifactId>
-    <version>1.90</version>
+    <version>1.91-SNAPSHOT</version>
<relativePath />
</parent>
diff --git a/src/spotbugs/spotbugs-excludes.xml b/src/spotbugs/spotbugs-excludes.xml
index 0971834a23..d3fe630c37 100644
--- a/src/spotbugs/spotbugs-excludes.xml
+++ b/src/spotbugs/spotbugs-excludes.xml
@@ -88,236 +88,6 @@
<Class name="hudson.tasks.Fingerprinter$FingerprintAction"/>
</Or>
</And>
-      <And>
-        <Bug …
```

Omit `FindReturnRef` SpotBugs visitor

---

pom.xml

Consistent with https://github.com/jenkinsci/plugin-pom/blob/master/pom.xml#L145-L149.

Add Hamcrest to `<dependencyManagement>` section

---

pom.xml

https://github.com/jenkinsci/plugin-pom/pull/631#issuecomment-1320960815

Use `project.basedir` rather than `maven.multiModuleProjectDirectory`

---

pom.xml

This mailing list has been archived.

Remove japanese mailing list from pom

---

pom.xml

Follow up of https://github.com/jenkinsci/plugin-pom/pull/703

Remove deprecated `display-info`-goal

---

pom.xml

Side-port of jenkinsci/plugin-pom#733 and jenkinsci/plugin-pom#742 to `jenkinsci/pom`.

Enable Spotless for automatic formatting

---

pom.xml

https://github.com/jenkinsci/license-maven-plugin/releases/tag/98.vd05d703fe349

Adapt maven-license-plugin changes

---

pom.xml

ref https://github.com/jenkinsci/stapler-maven-plugin/releases/tag/171.vfa_c6fd2e46a_a_

Adapt maven-stapler-plugin changes

---

pom.xml

- Keep list sorted
- Use property name consistent with artifact ID

Fixups to #460 and #462

---

pom.xml

Sideport of https://github.com/jenkinsci/plugin-pom/pull/816 to `jenkinsci/pom`.
See https://github.com/jenkinsci/plugin-pom/pull/816.

Upgrade `palantir-java-format` to Java 21 compatible release

---

pom.xml

Sideport of jenkinsci/plugin-pom#785 to `jenkinsci/pom`.

Fix Hamcrest versioning

---

pom.xml

Side-port of jenkinsci/plugin-pom#822 to `jenkinsci/pom`.

Make JUnit version a customizable property

---

pom.xml

Like https://github.com/jenkinsci/plugin-pom/pull/836 but for `jenkinsci/pom`.
No upper bounds annoyances in core, Stapler, Remoting, JTH, or File Leak Detector with these changes.

Remove unnecessary workarounds

---

pom.xml

Like https://github.com/jenkinsci/plugin-pom/pull/850, but for `jenkinsci/pom`.
See https://github.com/jenkinsci/plugin-pom/pull/850.

Define `maven.compiler.testRelease` in terms of `maven.compiler.release`

---

pom.xml

https://groups.google.com/g/jenkinsci-dev/c/gsXAqOQQEPc/m/C_EIMal6BAAJ

[JENKINS-73120] Require Java 17 in parent POM for core and core components

---

pom.xml

See https://github.com/jenkinsci/maven-hpi-plugin/pull/668

Require Maven 3.9.6 or later

---

pom.xml

https://github.com/jenkinsci/jelly/blob/fae50056c1478d31bc9f8664ed87cd0d77e16060/pom.xml#L123-L124
https://github.com/jenkinsci/stapler/blob/a2af4a86dbc2714b6f67f5dcf8f59832c00bc3d9/jelly/pom.xml#L16

Manage `jellydoc-maven-plugin`
